name = "lightchat"
main = "src/index.ts"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "lightchat"
database_id = "33cbe608-36a0-4522-8c00-7bc5191c0278"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "lightchat-media"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[triggers]
crons = ["0 3 * * *"]
